# Generated by Django 6.0 on 2026-07-07 10:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_address_options_address_address_type_and_more'),
        ('orders', '0002_order_production_refactor'),
        ('products', '0002_categoryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Reference to the Address record selected at checkout. May become NULL if the user deletes the address later. Use the snapshot fields for the authoritative delivery address.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, default='', help_text='Snapshot of the coupon code applied at checkout, if any. Stored for audit and customer-service reference.', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC timestamp when the order was first created.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total monetary discount applied to the order (coupon, loyalty points, promotional code, etc.). Stored as a positive value; subtracted during total calculation.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, default='', help_text="Free-text notes from the customer (e.g. delivery instructions) or internal staff remarks (e.g. 'fragile, handle with care')."),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(db_index=True, editable=False, help_text="Human-readable, globally unique order identifier. Auto-generated on first save in the format 'ORD-YYYYMMDD-<UUID4_short>'. Never reused, never editable after creation.", max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash On Delivery'), ('razorpay', 'Razorpay'), ('stripe', 'Stripe'), ('upi', 'UPI')], default='cod', help_text='The payment instrument chosen by the customer at checkout. For gateway-based methods (Razorpay, Stripe) the payment_id from the gateway transaction is stored in the linked Payment record.', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', help_text="Current payment lifecycle state, maintained by the payments app webhook handler.  Decoupled from order status so that an order can be 'shipped' while its payment is still 'pending' (e.g. COD).", max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Flat or calculated shipping fee added to the order. Zero for free-shipping promotions or digital products.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='snapshot_address_line_1',
            field=models.CharField(help_text='Primary address line (house/flat/building number and street).', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='snapshot_address_line_2',
            field=models.CharField(blank=True, default='', help_text='Secondary address line (apartment, suite, wing — optional).', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='snapshot_city',
            field=models.CharField(help_text='City / district of the delivery address.', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='snapshot_country',
            field=models.CharField(default='India', help_text='Country of the delivery address.', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='snapshot_full_name',
            field=models.CharField(help_text='Recipient full name as entered at checkout.', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='snapshot_landmark',
            field=models.CharField(blank=True, default='', help_text='Nearby landmark to assist the courier (optional).', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='snapshot_phone',
            field=models.CharField(help_text='Contact phone number for delivery queries.', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='snapshot_postal_code',
            field=models.CharField(help_text='PIN / ZIP / postal code.', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='snapshot_state',
            field=models.CharField(help_text='State / province of the delivery address.', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', help_text='Current fulfilment state of the order. Transitions: pending → confirmed → packed → shipped → delivered. Cancellation is allowed from any pre-delivered state.', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of (price × quantity) for all OrderItems before any discounts, tax, or shipping charges are applied.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total tax amount (GST / VAT) applied to the order. Derived from the tax rate configured in settings; stored denormalised for invoice / reporting accuracy.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Grand total charged to the customer. Formula: subtotal - discount + tax + shipping_charge. Denormalised here for fast display; recomputed by the service layer on every order write.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='UTC timestamp of the most recent change to this record.'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(help_text='The parent order this line item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Snapshot: unit price of the variant at the time of purchase (after any per-item discount but before order-level discount). This is the price-per-unit that will appear on invoices.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Live reference to the Product in the catalogue. May be NULL if the product was deleted after purchase. Always use snapshot fields for financial / display logic.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_image',
            field=models.URLField(blank=True, default='', help_text='Snapshot: absolute URL of the primary product image at checkout. Stored as a URL (not an ImageField) because the physical file may be replaced or deleted, but order history should always show the image the customer saw when they purchased.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(help_text="Snapshot: product name at the time of purchase (e.g. 'iPhone 15 Pro').", max_length=255),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Number of units of this variant ordered. Always ≥ 1; validated by the serializer.'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='sku',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Snapshot: Stock-Keeping Unit of the variant at the time of purchase. Indexed to support warehouse / fulfilment queries by SKU.', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total',
            field=models.DecimalField(decimal_places=2, help_text='Denormalised line total: price × quantity. Stored to avoid recomputing on every read and to lock in the value even if price logic changes in the future.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Live reference to the specific ProductVariant purchased (carries price, SKU, and stock at purchase time). May be NULL if the variant was deleted after purchase.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.productvariant'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variant_name',
            field=models.CharField(blank=True, default='', help_text="Snapshot: variant label at the time of purchase (e.g. '256GB / Space Black'). Empty for products with no variants.", max_length=100),
        ),
    ]
