# Generated by Django 6.0 on 2026-07-27 06:59

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_alter_order_address_alter_order_coupon_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Unique, case-insensitive coupon code.', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the coupon.')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', help_text='Type of discount (percentage or fixed amount).', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='The value of the discount (e.g. 10.00 for 10% or $10.00).', max_digits=10)),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum order subtotal required to apply this coupon.', max_digits=12)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount cap (applicable for percentage discount).', max_digits=10, null=True)),
                ('start_date', models.DateTimeField(help_text='DateTime when the coupon becomes valid.')),
                ('end_date', models.DateTimeField(help_text='DateTime when the coupon expires.')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle coupon status.')),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Total usage limit across all customers. None means unlimited.', null=True)),
                ('per_user_limit', models.PositiveIntegerField(default=1, help_text='Maximum number of times a single customer can use this coupon.')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times this coupon has been used.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='coupons.coupon')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coupon Usage',
                'verbose_name_plural': 'Coupon Usages',
            },
        ),
    ]
