# Generated by Django 6.0 on 2026-08-04 10:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
        ('products', '0006_product_average_rating_product_rating_1_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='auto_apply',
            field=models.BooleanField(default=False, help_text='If True, coupon is applied automatically.'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_scope',
            field=models.CharField(choices=[('entire_cart', 'Entire Cart'), ('specific_categories', 'Specific Categories'), ('specific_products', 'Specific Products'), ('product_combination', 'Product Combination')], default='entire_cart', help_text='The scope of applicability for this coupon.', max_length=30),
        ),
        migrations.AddField(
            model_name='coupon',
            name='first_order_only',
            field=models.BooleanField(default=False, help_text="If True, coupon can only be applied to a user's first order."),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_stackable',
            field=models.BooleanField(default=False, help_text='If True, this coupon can be combined with other coupons.'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_purchase_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum order subtotal allowed to apply this coupon.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_cart_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum quantity of any items in the cart required.', null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_product_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum quantity of target items required.', null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='priority',
            field=models.IntegerField(default=0, help_text='Priority order for auto-apply or sorting.'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount'), ('free_shipping', 'Free Shipping')], default='percentage', help_text='Type of discount (percentage, fixed amount, or free shipping).', max_length=20),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The value of the discount (e.g. 10.00 for 10% or $10.00). 0.00 for Free Shipping.', max_digits=10),
        ),
        migrations.CreateModel(
            name='CouponCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_categories', to='products.category')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupons.coupon')),
            ],
            options={
                'verbose_name': 'Coupon Category',
                'verbose_name_plural': 'Coupon Categories',
                'unique_together': {('coupon', 'category')},
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='coupons', through='coupons.CouponCategory', to='products.category'),
        ),
        migrations.CreateModel(
            name='CouponProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField(default=1)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupons.coupon')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_products', to='products.product')),
            ],
            options={
                'verbose_name': 'Coupon Product',
                'verbose_name_plural': 'Coupon Products',
                'unique_together': {('coupon', 'product')},
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='coupons', through='coupons.CouponProduct', to='products.product'),
        ),
    ]
