# Generated by Django 6.0 on 2026-07-07 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_alter_order_address_alter_order_coupon_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cod', 'Cash On Delivery'), ('razorpay', 'Razorpay'), ('stripe', 'Stripe')], db_index=True, default='razorpay', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount captured in standard currency units.', max_digits=12)),
                ('transaction_id', models.CharField(blank=True, db_index=True, default='', help_text='Gateway-specific payment transaction ID (e.g. pay_K1j2u3z).', max_length=100)),
                ('razorpay_order_id', models.CharField(blank=True, db_index=True, default='', help_text='Razorpay Order ID created in pre-checkout.', max_length=100)),
                ('raw_response', models.JSONField(blank=True, help_text='Full response JSON received from the payment gateway.', null=True)),
                ('error_message', models.TextField(blank=True, default='', help_text='Detailed failure reason returned by the gateway.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(help_text='The order associated with this transaction.', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.order')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['razorpay_order_id'], name='idx_txn_rzp_order'), models.Index(fields=['transaction_id'], name='idx_txn_gateway_id')],
            },
        ),
    ]
